### PR TITLE
Modernized RobustStats.jl

### PR DESCRIPTION
**Pull request by joefowler**
@maximsch2 and I have made multiple changes to modernize RobustStats.jl.  (It works under Julia 0.5, but not 0.6 yet.) 

Would you consider either (1) accepting this pull request, or (2) supporting a request to point the julia METADATA entry to this fork instead of the original?

### CODE REVIEW

**Comment by maximsch2** [comment]
Thanks for making the PR, @joefowler. I've just added 0.6 to Travis explicitly and we are actually passing existing tests on 0.6 (meaning 0.6-alpha) as well as nightly.

**Comment by joefowler** [comment]
Whoa! I had no idea we were so close to passing Julia 0.6 tests. Thanks for making that happen. (If only I were in this state on my other projects...)

**Comment by mrxiaohe** [comment]
@joefowler @maximsch2 I just approved the pull request. let me know if you have any other questions.

**Comment by maximsch2** [comment]
Awesome, thank you! 

Would you mind also tagging a new release in METADATA so that `Pkg.add` gets the newest code? To make it easier, you might consider installing attobot: https://github.com/attobot/attobot

**Pull request merged**
